-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLTx/IEEE_8021513_TX_src_read_frame_from_ram.vhd
-- Created: 2024-11-21 09:59:25
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IEEE_8021513_TX_src_read_frame_from_ram
-- Source Path: HDLTx/full_tx/store_frame_in_ram/read_frame_from_ram
-- Hierarchy Level: 2
-- Model version: 4.222
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.IEEE_8021513_TX_src_full_tx_pac.ALL;

ENTITY IEEE_8021513_TX_src_read_frame_from_ram IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb_1_2_0                         :   IN    std_logic;
        start_reading                     :   IN    std_logic;
        ram_size                          :   IN    std_logic_vector(24 DOWNTO 0);  -- ufix25
        bits_per_subcarrier               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        cp_len_in                         :   IN    std_logic_vector(2 DOWNTO 0);  -- boolean [3]
        ready                             :   IN    std_logic;
        rd_addr                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        valid_out                         :   OUT   std_logic;
        bits_per_subcarrier_out           :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        init                              :   OUT   std_logic_vector(12 DOWNTO 0);  -- boolean [13]
        new_rsvd                          :   OUT   std_logic;
        cp_len                            :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END IEEE_8021513_TX_src_read_frame_from_ram;


ARCHITECTURE rtl OF IEEE_8021513_TX_src_read_frame_from_ram IS

  -- Component Declarations
  COMPONENT IEEE_8021513_TX_src_bits_selector
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          bits_per_subcarrier             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          bits_per_subcarrier_out         :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
          );
  END COMPONENT;

  COMPONENT IEEE_8021513_TX_src_init_selector
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          init                            :   OUT   std_logic_vector(12 DOWNTO 0)  -- boolean [13]
          );
  END COMPONENT;

  COMPONENT IEEE_8021513_TX_src_Compare_To_Zero1
    PORT( u                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          y                               :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT IEEE_8021513_TX_src_cp_len_creator
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          cp_len_in                       :   IN    std_logic_vector(2 DOWNTO 0);  -- boolean [3]
          cp_len                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : IEEE_8021513_TX_src_bits_selector
    USE ENTITY work.IEEE_8021513_TX_src_bits_selector(rtl);

  FOR ALL : IEEE_8021513_TX_src_init_selector
    USE ENTITY work.IEEE_8021513_TX_src_init_selector(rtl);

  FOR ALL : IEEE_8021513_TX_src_Compare_To_Zero1
    USE ENTITY work.IEEE_8021513_TX_src_Compare_To_Zero1(rtl);

  FOR ALL : IEEE_8021513_TX_src_cp_len_creator
    USE ENTITY work.IEEE_8021513_TX_src_cp_len_creator(rtl);

  -- Signals
  SIGNAL start_reading_1                  : std_logic;
  SIGNAL ram_size_unsigned                : unsigned(24 DOWNTO 0);  -- ufix25
  SIGNAL stateControl                     : std_logic;
  SIGNAL stateControl_1                   : std_logic;
  SIGNAL enb_1_2_0_gated                  : std_logic;
  SIGNAL count_step                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL count_reset                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_addr_1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL count                            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Switch1_out1                     : std_logic;
  SIGNAL Unit_Delay1_out1                 : std_logic;
  SIGNAL Relational_Operator1_out1        : std_logic;
  SIGNAL Logical_Operator5_out1           : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL count_1                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL count_2                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL stateControl_2                   : std_logic;
  SIGNAL stateControl_3                   : std_logic;
  SIGNAL enb_1_2_0_gated_1                : std_logic;
  SIGNAL Delay6_reg                       : vector_of_unsigned16(0 TO 1);  -- ufix16 [2]
  SIGNAL Delay6_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL stateControl_4                   : std_logic;
  SIGNAL stateControl_5                   : std_logic;
  SIGNAL enb_1_2_0_gated_2                : std_logic;
  SIGNAL Delay2_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL stateControl_6                   : std_logic;
  SIGNAL stateControl_7                   : std_logic;
  SIGNAL enb_1_2_0_gated_3                : std_logic;
  SIGNAL Delay7_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay7_out1                      : std_logic;
  SIGNAL stateControl_9                   : std_logic;
  SIGNAL stateControl_10                  : std_logic;
  SIGNAL enb_1_2_0_gated_4                : std_logic;
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL bits_selector_out1               : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL bits_selector_out1_unsigned      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL stateControl_11                  : std_logic;
  SIGNAL stateControl_12                  : std_logic;
  SIGNAL enb_1_2_0_gated_5                : std_logic;
  SIGNAL Delay5_out1                      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL init_selector_out1               : std_logic_vector(12 DOWNTO 0);  -- boolean [13]
  SIGNAL stateControl_13                  : std_logic;
  SIGNAL stateControl_14                  : std_logic;
  SIGNAL enb_1_2_0_gated_6                : std_logic;
  SIGNAL Delay3_out1                      : std_logic_vector(12 DOWNTO 0);  -- boolean [13]
  SIGNAL start_reading_2                  : std_logic;
  SIGNAL count_step_1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL count_from                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL count_reset_1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL HDL_Counter2_out1                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL count_3                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL count_4                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL count_5                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Zero1_out1            : std_logic;
  SIGNAL Logical_Operator4_out1           : std_logic;
  SIGNAL stateControl_15                  : std_logic;
  SIGNAL stateControl_16                  : std_logic;
  SIGNAL enb_1_2_0_gated_7                : std_logic;
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL cp_len_creator_out1              : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL cp_len_creator_out1_unsigned     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL stateControl_17                  : std_logic;
  SIGNAL stateControl_18                  : std_logic;
  SIGNAL enb_1_2_0_gated_8                : std_logic;
  SIGNAL Delay4_out1                      : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  u_bits_selector : IEEE_8021513_TX_src_bits_selector
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_2_0 => enb_1_2_0,
              rd_addr => std_logic_vector(rd_addr_1),  -- uint16
              bits_per_subcarrier => bits_per_subcarrier,  -- ufix4
              bits_per_subcarrier_out => bits_selector_out1  -- ufix4
              );

  u_init_selector : IEEE_8021513_TX_src_init_selector
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_2_0 => enb_1_2_0,
              rd_addr => std_logic_vector(rd_addr_1),  -- uint16
              init => init_selector_out1  -- boolean [13]
              );

  u_Compare_To_Zero1 : IEEE_8021513_TX_src_Compare_To_Zero1
    PORT MAP( u => std_logic_vector(HDL_Counter2_out1),  -- uint8
              y => Compare_To_Zero1_out1
              );

  u_cp_len_creator : IEEE_8021513_TX_src_cp_len_creator
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_2_0 => enb_1_2_0,
              rd_addr => std_logic_vector(rd_addr_1),  -- uint16
              cp_len_in => cp_len_in,  -- boolean [3]
              cp_len => cp_len_creator_out1  -- uint8
              );

  start_reading_1 <= start_reading;

  ram_size_unsigned <= unsigned(ram_size);

  stateControl <= '1';

  delayMatch8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        stateControl_1 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        stateControl_1 <= stateControl;
      END IF;
    END IF;
  END PROCESS delayMatch8_process;


  enb_1_2_0_gated <= stateControl_1 AND enb_1_2_0;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  count_step <= to_unsigned(16#0001#, 16);

  count_reset <= to_unsigned(16#0000#, 16);

  count <= rd_addr_1 + count_step;

  Unit_Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Unit_Delay1_out1 <= '0';
      ELSIF enb_1_2_0_gated = '1' THEN
        Unit_Delay1_out1 <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay1_process;


  
  Relational_Operator1_out1 <= '1' WHEN ram_size_unsigned = resize(rd_addr_1, 25) ELSE
      '0';

  Logical_Operator5_out1 <= start_reading OR Relational_Operator1_out1;

  
  Switch1_out1 <= Unit_Delay1_out1 WHEN Logical_Operator5_out1 = '0' ELSE
      start_reading;

  AND_out1 <= Switch1_out1 AND ready;

  
  count_1 <= rd_addr_1 WHEN AND_out1 = '0' ELSE
      count;

  
  count_2 <= count_1 WHEN start_reading_1 = '0' ELSE
      count_reset;

  HDL_Counter1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        rd_addr_1 <= to_unsigned(16#0000#, 16);
      ELSIF enb_1_2_0 = '1' THEN
        rd_addr_1 <= count_2;
      END IF;
    END IF;
  END PROCESS HDL_Counter1_process;


  stateControl_2 <= '1';

  delayMatch6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        stateControl_3 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        stateControl_3 <= stateControl_2;
      END IF;
    END IF;
  END PROCESS delayMatch6_process;


  enb_1_2_0_gated_1 <= stateControl_3 AND enb_1_2_0;

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay6_reg <= (OTHERS => to_unsigned(16#0000#, 16));
      ELSIF enb_1_2_0_gated_1 = '1' THEN
        Delay6_reg(0) <= rd_addr_1;
        Delay6_reg(1) <= Delay6_reg(0);
      END IF;
    END IF;
  END PROCESS Delay6_process;

  Delay6_out1 <= Delay6_reg(1);

  stateControl_4 <= '1';

  delayMatch2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        stateControl_5 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        stateControl_5 <= stateControl_4;
      END IF;
    END IF;
  END PROCESS delayMatch2_process;


  enb_1_2_0_gated_2 <= stateControl_5 AND enb_1_2_0;

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay2_out1 <= to_unsigned(16#0000#, 16);
      ELSIF enb_1_2_0_gated_2 = '1' THEN
        Delay2_out1 <= Delay6_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  rd_addr <= std_logic_vector(Delay2_out1);

  stateControl_6 <= '1';

  delayMatch7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        stateControl_7 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        stateControl_7 <= stateControl_6;
      END IF;
    END IF;
  END PROCESS delayMatch7_process;


  enb_1_2_0_gated_3 <= stateControl_7 AND enb_1_2_0;

  Delay7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay7_reg <= (OTHERS => '0');
      ELSIF enb_1_2_0_gated_3 = '1' THEN
        Delay7_reg(0) <= AND_out1;
        Delay7_reg(1) <= Delay7_reg(0);
      END IF;
    END IF;
  END PROCESS Delay7_process;

  Delay7_out1 <= Delay7_reg(1);

  stateControl_9 <= '1';

  delayMatch_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        stateControl_10 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        stateControl_10 <= stateControl_9;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  enb_1_2_0_gated_4 <= stateControl_10 AND enb_1_2_0;

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay_out1 <= '0';
      ELSIF enb_1_2_0_gated_4 = '1' THEN
        Delay_out1 <= Delay7_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  bits_selector_out1_unsigned <= unsigned(bits_selector_out1);

  stateControl_11 <= '1';

  delayMatch5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        stateControl_12 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        stateControl_12 <= stateControl_11;
      END IF;
    END IF;
  END PROCESS delayMatch5_process;


  enb_1_2_0_gated_5 <= stateControl_12 AND enb_1_2_0;

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay5_out1 <= to_unsigned(16#0#, 4);
      ELSIF enb_1_2_0_gated_5 = '1' THEN
        Delay5_out1 <= bits_selector_out1_unsigned;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  bits_per_subcarrier_out <= std_logic_vector(Delay5_out1);

  stateControl_13 <= '1';

  delayMatch3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        stateControl_14 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        stateControl_14 <= stateControl_13;
      END IF;
    END IF;
  END PROCESS delayMatch3_process;


  enb_1_2_0_gated_6 <= stateControl_14 AND enb_1_2_0;

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay3_out1 <= (OTHERS => '0');
      ELSIF enb_1_2_0_gated_6 = '1' THEN
        Delay3_out1 <= init_selector_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  start_reading_2 <= start_reading;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 174
  count_step_1 <= to_unsigned(16#01#, 8);

  count_from <= to_unsigned(16#00#, 8);

  count_reset_1 <= to_unsigned(16#00#, 8);

  count_3 <= HDL_Counter2_out1 + count_step_1;

  
  need_to_wrap <= '1' WHEN HDL_Counter2_out1 = to_unsigned(16#AE#, 8) ELSE
      '0';

  
  count_value <= count_3 WHEN need_to_wrap = '0' ELSE
      count_from;

  
  count_4 <= HDL_Counter2_out1 WHEN Delay7_out1 = '0' ELSE
      count_value;

  
  count_5 <= count_4 WHEN start_reading_2 = '0' ELSE
      count_reset_1;

  HDL_Counter2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        HDL_Counter2_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb_1_2_0 = '1' THEN
        HDL_Counter2_out1 <= count_5;
      END IF;
    END IF;
  END PROCESS HDL_Counter2_process;


  Logical_Operator4_out1 <= Delay7_out1 AND Compare_To_Zero1_out1;

  stateControl_15 <= '1';

  delayMatch1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        stateControl_16 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        stateControl_16 <= stateControl_15;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  enb_1_2_0_gated_7 <= stateControl_16 AND enb_1_2_0;

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay1_out1 <= '0';
      ELSIF enb_1_2_0_gated_7 = '1' THEN
        Delay1_out1 <= Logical_Operator4_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  cp_len_creator_out1_unsigned <= unsigned(cp_len_creator_out1);

  stateControl_17 <= '1';

  delayMatch4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        stateControl_18 <= '0';
      ELSIF enb_1_2_0 = '1' THEN
        stateControl_18 <= stateControl_17;
      END IF;
    END IF;
  END PROCESS delayMatch4_process;


  enb_1_2_0_gated_8 <= stateControl_18 AND enb_1_2_0;

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay4_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb_1_2_0_gated_8 = '1' THEN
        Delay4_out1 <= cp_len_creator_out1_unsigned;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  cp_len <= std_logic_vector(Delay4_out1);

  valid_out <= Delay_out1;

  init <= Delay3_out1;

  new_rsvd <= Delay1_out1;

END rtl;

