-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLTx/IEEE_8021513_TX_src_reduced_ldpc.vhd
-- Created: 2024-11-21 09:59:25
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IEEE_8021513_TX_src_reduced_ldpc
-- Source Path: HDLTx/full_tx/payload_full/reduced_ldpc
-- Hierarchy Level: 2
-- Model version: 4.222
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IEEE_8021513_TX_src_reduced_ldpc IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        data_in                           :   IN    std_logic;
        ctrl_in_start                     :   IN    std_logic;
        ctrl_in_end                       :   IN    std_logic;
        ctrl_in_valid                     :   IN    std_logic;
        data_out                          :   OUT   std_logic;
        ctrl_out_start                    :   OUT   std_logic;
        ctrl_out_end                      :   OUT   std_logic;
        ctrl_out_valid                    :   OUT   std_logic;
        next_frame                        :   OUT   std_logic
        );
END IEEE_8021513_TX_src_reduced_ldpc;


ARCHITECTURE rtl OF IEEE_8021513_TX_src_reduced_ldpc IS

  -- Component Declarations
  COMPONENT IEEE_8021513_TX_src_Hc_12S_B80
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          in0                             :   IN    std_logic;
          in1_start                       :   IN    std_logic;
          in1_end                         :   IN    std_logic;
          in1_valid                       :   IN    std_logic;
          out0                            :   OUT   std_logic;
          out1_start                      :   OUT   std_logic;
          out1_end                        :   OUT   std_logic;
          out1_valid                      :   OUT   std_logic;
          out2                            :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : IEEE_8021513_TX_src_Hc_12S_B80
    USE ENTITY work.IEEE_8021513_TX_src_Hc_12S_B80(rtl);

  -- Signals
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL Delay1_out1_start                : std_logic;
  SIGNAL Delay1_out1_end                  : std_logic;
  SIGNAL Delay1_out1_valid                : std_logic;
  SIGNAL Hc_12S_B80_out1                  : std_logic;
  SIGNAL Hc_12S_B80_out2_start            : std_logic;
  SIGNAL Hc_12S_B80_out2_end              : std_logic;
  SIGNAL Hc_12S_B80_out2_valid            : std_logic;
  SIGNAL Hc_12S_B80_out3                  : std_logic;
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Delay3_out1_start                : std_logic;
  SIGNAL Delay3_out1_end                  : std_logic;
  SIGNAL Delay3_out1_valid                : std_logic;
  SIGNAL Delay4_out1                      : std_logic;

BEGIN
  u_Hc_12S_B80 : IEEE_8021513_TX_src_Hc_12S_B80
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              in0 => Delay_out1,
              in1_start => Delay1_out1_start,
              in1_end => Delay1_out1_end,
              in1_valid => Delay1_out1_valid,
              out0 => Hc_12S_B80_out1,
              out1_start => Hc_12S_B80_out2_start,
              out1_end => Hc_12S_B80_out2_end,
              out1_valid => Hc_12S_B80_out2_valid,
              out2 => Hc_12S_B80_out3
              );

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay_out1 <= data_in;
      END IF;
    END IF;
  END PROCESS Delay_process;


  c_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay1_out1_start <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1_start <= ctrl_in_start;
      END IF;
    END IF;
  END PROCESS c_process;


  c_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay1_out1_end <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1_end <= ctrl_in_end;
      END IF;
    END IF;
  END PROCESS c_1_process;


  c_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay1_out1_valid <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1_valid <= ctrl_in_valid;
      END IF;
    END IF;
  END PROCESS c_2_process;


  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay2_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay2_out1 <= Hc_12S_B80_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  c_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay3_out1_start <= '0';
      ELSIF enb = '1' THEN
        Delay3_out1_start <= Hc_12S_B80_out2_start;
      END IF;
    END IF;
  END PROCESS c_3_process;


  c_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay3_out1_end <= '0';
      ELSIF enb = '1' THEN
        Delay3_out1_end <= Hc_12S_B80_out2_end;
      END IF;
    END IF;
  END PROCESS c_4_process;


  c_5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay3_out1_valid <= '0';
      ELSIF enb = '1' THEN
        Delay3_out1_valid <= Hc_12S_B80_out2_valid;
      END IF;
    END IF;
  END PROCESS c_5_process;


  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay4_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay4_out1 <= Hc_12S_B80_out3;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  data_out <= Delay2_out1;

  ctrl_out_start <= Delay3_out1_start;

  ctrl_out_end <= Delay3_out1_end;

  ctrl_out_valid <= Delay3_out1_valid;

  next_frame <= Delay4_out1;

END rtl;

