-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLTx/IEEE_8021513_TX_src_Compare_To_Constant.vhd
-- Created: 2024-11-21 09:59:25
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IEEE_8021513_TX_src_Compare_To_Constant
-- Source Path: HDLTx/full_tx/payload_full/tone_mapping/Compare To Constant
-- Hierarchy Level: 3
-- Model version: 4.222
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IEEE_8021513_TX_src_Compare_To_Constant IS
  PORT( u                                 :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33
        y                                 :   OUT   std_logic
        );
END IEEE_8021513_TX_src_Compare_To_Constant;


ARCHITECTURE rtl OF IEEE_8021513_TX_src_Compare_To_Constant IS

  -- Signals
  SIGNAL u_signed                         : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL Constant_out1                    : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL Compare_out1                     : std_logic;

BEGIN
  u_signed <= signed(u);

  Constant_out1 <= to_signed(1, 33);

  
  Compare_out1 <= '1' WHEN u_signed = Constant_out1 ELSE
      '0';

  y <= Compare_out1;

END rtl;

