-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLTx/IEEE_8021513_TX_src_Compare_To_Zero.vhd
-- Created: 2024-11-21 09:59:25
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IEEE_8021513_TX_src_Compare_To_Zero
-- Source Path: HDLTx/full_tx/store_frame_in_ram/write_frame_to_ram/Compare To Zero
-- Hierarchy Level: 3
-- Model version: 4.222
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IEEE_8021513_TX_src_Compare_To_Zero IS
  PORT( u                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        y                                 :   OUT   std_logic
        );
END IEEE_8021513_TX_src_Compare_To_Zero;


ARCHITECTURE rtl OF IEEE_8021513_TX_src_Compare_To_Zero IS

  -- Signals
  SIGNAL u_unsigned                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_out1                     : std_logic;

BEGIN
  u_unsigned <= unsigned(u);

  Constant_out1 <= to_unsigned(16#0000#, 16);

  
  Compare_out1 <= '1' WHEN u_unsigned /= Constant_out1 ELSE
      '0';

  y <= Compare_out1;

END rtl;

